### ISSUE TITLE
Test cases ...

### ISSUE THREAD

**Issue by misalyogeshwar** [jwasham/practice-cpp#2]
Hi @jwasham ,  How do you write these test cases?  I mean the code. How does this work? Any source I can learn it or refer it from?

Also thanks for your amazing work! 👍 😄

**Comment by jwasham** [comment]
Hi!
It's been a few months, so I'm trying to remember.
I'm using CLion, an IDE that recognizes the CMakeList files and lets me build/run each directory individually. I don't run make myself.
Some directories have separate test classes that are called from within the main.cc in that directory.

**Comment by misalyogeshwar** [comment]
Okay.. Thanks again 👍
